/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	darkMode: 'class',
	theme: {
		extend: {
			colors: {
				"outline-variant": "#adb3b4",
				"surface-tint": "#5f5e5e",
				"on-secondary-container": "#4f5253",
				"on-primary-fixed": "#403f3f",
				"primary-dim": "#535252",
				"surface-variant": "#dde4e5",
				"on-primary": "#faf7f6",
				"surface-container-lowest": "#ffffff",
				"error": "#9f403d",
				"inverse-on-surface": "#9c9d9d",
				"surface-bright": "#f9f9f9",
				"on-surface": "#2d3435",
				"on-primary-container": "#525151",
				"on-tertiary": "#f4faff",
				"primary-fixed": "#e5e2e1",
				"background": "#f9f9f9",
				"tertiary": "#486272",
				"on-secondary": "#f7f9fa",
				"surface-dim": "#d4dbdd",
				"on-surface-variant": "#5a6061",
				"primary-fixed-dim": "#d7d4d3",
				"surface-container-high": "#e4e9ea",
				"tertiary-fixed": "#d0ecff",
				"outline": "#757c7d",
				"secondary": "#5c6060",
				"on-tertiary-fixed-variant": "#486272",
				"tertiary-dim": "#3c5666",
				"tertiary-fixed-dim": "#c2def0",
				"on-error-container": "#752121",
				"inverse-surface": "#0c0f0f",
				"secondary-fixed-dim": "#d2d5d5",
				"primary": "#5f5e5e",
				"error-dim": "#4e0309",
				"tertiary-container": "#d0ecff",
				"on-secondary-fixed": "#3c4040",
				"on-background": "#2d3435",
				"inverse-primary": "#ffffff",
				"surface-container": "#ebeeef",
				"secondary-dim": "#505454",
				"on-primary-fixed-variant": "#5c5b5b",
				"secondary-container": "#e1e3e3",
				"primary-container": "#e5e2e1",
				"surface": "#f9f9f9",
				"surface-container-highest": "#dde4e5",
				"error-container": "#fe8983",
				"secondary-fixed": "#e1e3e3",
				"on-secondary-fixed-variant": "#595c5d",
				"on-error": "#fff7f6",
				"surface-container-low": "#f2f4f4",
				"on-tertiary-container": "#3e5868",
				"on-tertiary-fixed": "#2c4655"
			},
			fontFamily: {
				"headline": ["Space Grotesk", "sans-serif"],
				"body": ["Inter", "sans-serif"],
				"label": ["Inter", "sans-serif"]
			},
			borderRadius: {
				"DEFAULT": "0.125rem",
				"lg": "0.25rem",
				"xl": "0.5rem",
				"full": "0.75rem"
			},
		},
	},
	plugins: [
		require('@tailwindcss/typography'),
		require('@tailwindcss/container-queries'),
	],
}
